alpine-version: "3.23.3"
headless: true

vm:
  cpus: 4
  memory: 4096
  mac: "52:54:00:ab:cd:01"

mounts:
  - host: ~/.claude
  - host: ~/.cache/aibox/apk
    guest: /etc/apk/cache

provision:
  - apk update
  - apk add curl bash screen git
  - apk add libgcc libstdc++ ripgrep gcompat
  - sudo -u {{username}} -i sh -c "curl -fsSL https://claude.ai/install.sh | bash"
